### ISSUE TITLE
Double license

### ISSUE THREAD

**Issue by kaosdynamics** [creotiv/jquery-photowall#11]
Could you license this project under two different license (e.g. a GPL-like one [GPLv3] and BSD-like one [MIT])?

**Comment by creotiv** [comment]
Yes i can. I will add MIT license at Monday.

**Comment by creotiv** [comment]
Yes i can. I will add MIT license at Monday.

Kindly yours,
Andrey Nikishaev

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666

On Sat, Apr 7, 2012 at 4:35 AM, PreziuSoftware Corporation <
reply@reply.github.com

**Comment by kaosdynamics** [comment]
great! :) thank you :)

**Comment by creotiv** [comment]
You are welcome)

**Comment by creotiv** [comment]
Added.
