### ISSUE TITLE
No size image in Safari

### ISSUE THREAD

**Issue by Clem-** [creotiv/jquery-photowall#14]
When a photo is displayed and then, the user comes back to it, the photo has no size (width: 0, height: 0)
Tested with Safari 5.1.7

**Comment by creotiv** [comment]
Just tested under Safari 5.1.7(Windows) all works fine. What OS do you have?

**Comment by Clem-** [comment]
OSX Lion (10.7.4)
I'm currently trying to debug it...

**Comment by Clem-** [comment]
Alright, so it seems like the issue is in this line :

``` javascript
img.attr('src',ShowBox._images[ShowBox._current][ind][0])
.load(function(){
            var iW = $(this).width();
            var iH = $(this).height();
            $(this).attr({
                width:iW,
                height:iH
            }).fadeIn(400);
```

The load event is triggered too soon for the width and height parameters to be written in the object.
It results with a `$(this).width() = 0` and `$(this).height() = 0`

Because when I put a breakpoint after the `.load`, and then, execute the code, the value of width and height in the object are well written.

Something must be wrong with the load event of jQuery. (I run jQuery 1.7.2)

**Comment by Clem-** [comment]
Well, some updates..
This is an issue with cache. When I change this line in order to add some randomness in the image url, like :

``` javascript
img.attr('src',ShowBox._images[ShowBox._current][ind][0]+"?"+Math.random())
```

There is no more problem at all.

My guess is : when an image is in cache, the load event of jQuery is not triggered properly.

**Edit:** It's confirmed by the fact that, if I clear my cache when I'm running your demo (http://creotiv.github.com/jquery-photowall/example.html), a previously "no-size image" is displayed again.

**Edit2:** Well, here's an interesting quote from jQuery Load Event Documentation :

> **Caveats of the load event when used with images**
> 
> A common challenge developers attempt to solve using the .load() shortcut is to execute a function when an image (or collection of images) have completely loaded. There are several known caveats with this that should be noted. These are:
> - It doesn't work consistently nor reliably cross-browser
> - It doesn't fire correctly in WebKit if the image src is set to the same src as before
> - It doesn't correctly bubble up the DOM tree
> - **Can cease to fire for images that already live in the browser's cache**

**Comment by creotiv** [comment]
Thanks for debug, i will add this to new release.

**Comment by Clem-** [comment]
Using `prop()` function solves the issue :

``` javascript
img.attr('src',ShowBox._images[ShowBox._current][ind][0])
.load(function(){
            var iW = $(this).prop('width');
            var iH = $(this).prop('height');
            $(this).attr({
                width:iW,
                height:iH
            }).fadeIn(400);
            $('#showbox-loader').hide();   
            $('#showbox .showbox-menubar').show();
            ShowBox.RESIZE();
        });
```

**Comment by creotiv** [comment]
Thanks for the patch and your work)
