### ISSUE TITLE
IE9 Photo box does not display the image

### ISSUE THREAD

**Issue by patrickb17** [creotiv/jquery-photowall#17]
The fullscreen photo box does not display the image when clicking on a thumbnail in internet explorer 9.

You will just see a blank black popup with the social widgets on the top!

**Comment by creotiv** [comment]
Thanks, i already know about this bug, try to fix it ASAP.

Kindly yours,
Andrey Nikishaev

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by patrickb17** [comment]
Awesome! Can you please notify me once it's fixed.

I installed this gallery on a high traffic website, and the clients 
loves it except the ie users cant use the gallery :)

Thanks

**Comment by creotiv** [comment]
Just deployed patch for IE. Please download fresh code.

Kindly yours,
Andrey Nikishaev

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by patrickb17** [comment]
Awesome, Thank you very much!

**Comment by stacehamilton** [comment]
It would seem i am having troubles with this issue also. I have downloaded the latest build but still not showing.  seems as though that if i remove my own CSS file it works but i do need my own styles.  I have tried it in chrome and works fine with my css file running. any ideas?  thank you.
