### ISSUE TITLE
How do I force the caption to show?

### ISSUE THREAD

**Issue by graphicallychallenged** [creotiv/jquery-photowall#18]

**Comment by mariiine** [comment]
Would be very useful to display captions :)

**Comment by creotiv** [comment]
For now there are no caption support. You can just give caption for gallery.

Kindly yours,
Andrey Nikishaev

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666
