### ISSUE TITLE
IE9 won't display photo

### ISSUE THREAD

**Issue by stacehamilton** [creotiv/jquery-photowall#22]
Hi I commented on closed issue number 17 but wasnt sure if it would work since it's closed.   It would seem i am having the same troubles with this issue also. I have downloaded the latest build but still not showing. seems as though that if i remove my own CSS file it works but i do need my own styles. I have tried it in chrome and works fine with my css file running. any ideas? thank you.

**Comment by creotiv** [comment]
If you breaking plugin css style with your own, then i can't help you. This
plugin does not supporting user styling.

Kindly yours,
Andrey Nikishaev

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by stacehamilton** [comment]
Ok.  Appeared that it was the call of @font-face which was breaking it.
