### ISSUE TITLE
Limited Images

### ISSUE THREAD

**Issue by umarmughal** [creotiv/jquery-photowall#7]
Hi, This is excellent photo wall but problem is i can only see 44 images under my gallery when there are more images, whatever gallery i choose i only see 44 images on wall .. why is like that? please advice .. thanks

**Comment by creotiv** [comment]
Please give me the link to your code(for example here https://gist.github.com/) and give me link to your gallery.

**Comment by creotiv** [comment]
It really strange, i will check it tomorrow.

вторник, 3 января 2012 г. пользователь Umar <
reply@reply.github.com>
писал:

> Hi, the code is all yours i dint change anything .. a little modification
> in HTML file which you can see here https://gist.github.com/1555287 .. and
> the gallery i am using is here 50BestNaturePhotos | 103406122733718121972
> 
> I want to tell you some weird thing i am facing which is its missing
> first 6 pictures from album and if i change "lineMaxHeight" to suppose 240
> it shows me two more images but still miss 4 images from start, i am not
> programer so not understanding the issue .. please advice.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/creotiv/jquery-photowall/issues/7#issuecomment-3341056

## 

Best regards,

Andrey Nikishaev

Blog           http://creotiv.in.ua/
Skype         creotiv.in.ua

**Comment by creotiv** [comment]
Fixed this bug. Please download new release of plugin.

Thanks for your help)

**Comment by umarmughal** [comment]
Thanks for all your help .. i am downloading it now and testing ... :)

**Comment by umarmughal** [comment]
Just downloaded and tried and its working fine .. but when i tried different gallery so its not displaying anything .. gallery id is 5459960719130526721 user is same .. with this id you can try yourself

**Comment by creotiv** [comment]
Because it's not exist
look https://picasaweb.google.com/data/feed/api/user/103406122733718121972/albumid/5459960719130526721/?alt=json&fields=entry(gphoto:id,title,media:group(media:thumbnail,media:content))&imgmax=720&callback=jQuery171038834579405374825_1325624034177&_=1325624034186

Or maybe it's not public.

**Comment by umarmughal** [comment]
Yes you are right :) ... thanks for the reply and fixing the work .. Great Work

**Comment by creotiv** [comment]
You are welcome)
